<a href="https://colab.research.google.com/github/kzeynep/Python_Atil_hoca/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [19]:
df = pd.read_csv('6-bank_customers.csv')

In [20]:
df.columns

Index(['age', 'job_satisfaction', 'balance', 'duration_last_call',
       'num_contacts_last_month', 'has_housing_loan', 'has_personal_loan',
       'communication_type', 'days_since_last_contact',
       'campaign_response_score', 'subscribed'],
      dtype='object')

In [21]:
# Scenario: Predicting whether a customer will subscribe to a term deposit (bank marketing use case) == Bir müşterinin vadeli mevduat hesabı açıp açmayacağını tahmin etmek (banka pazarlama kullanım örneği)

In [22]:
df.head()

age  job_satisfaction   balance  duration_last_call  \
0 -0.377957          1.043895  1.043494           -0.101838   
1 -0.325259          1.276263 -0.686123           -2.463205   
2  0.739019         -0.600903 -0.177294            1.335714   
3  0.474312         -1.103002  1.189936           -0.800186   
4  0.927365          1.114796  0.080284            1.261064   

   num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                -1.617442          0.402713           0.913601   
1                -0.489426         -0.240715          -1.469496   
2                -0.817332         -0.790047           1.457365   
3                 0.912377         -0.406451          -1.130950   
4                 0.761179          0.921563           0.440832   

   communication_type  days_since_last_contact  campaign_response_score  \
0           -0.067192                 0.175471                -1.049646   
1            1.006633                -0.833692                 0.957744   
2           -0.218981                 0.878643                -1.257740   
3            1.985111                 1.379029                 1.041768   
4            0.184645                -1.567739                -0.142107   

   subscribed  
0           0  
1           0  
2           0  
3           1  
4           1

In [23]:
df.describe()

age  job_satisfaction      balance  duration_last_call  \
count  1000.000000       1000.000000  1000.000000         1000.000000   
mean     -0.015084          0.031559     0.045069           -0.020771   
std       1.021848          1.004281     1.006910            1.392738   
min      -3.718638         -3.116027    -3.534257           -4.999018   
25%      -0.685005         -0.657545    -0.647051           -1.057938   
50%      -0.030546          0.045869     0.040586            0.204506   
75%       0.662124          0.701601     0.731615            1.061181   
max       2.765266          2.658705     3.357941            3.477210   

       num_contacts_last_month  has_housing_loan  has_personal_loan  \
count              1000.000000       1000.000000        1000.000000   
mean                  0.016769         -0.042135          -0.025139   
std                   1.268761          1.029279           1.267490   
min                  -2.587178         -3.250031          -4.932878   
25%                  -0.981320         -0.722970          -0.855392   
50%                  -0.317137         -0.022343           0.148199   
75%                   1.017388          0.596557           1.020255   
max                   3.954873          3.206344           2.343380   

       communication_type  days_since_last_contact  campaign_response_score  \
count         1000.000000              1000.000000              1000.000000   
mean             0.058969                -0.015637                 0.022327   
std              0.992629                 1.000664                 1.135131   
min             -3.187779                -2.819987                -2.071129   
25%             -0.598669                -0.693330                -1.050201   
50%              0.052208                 0.018807                -0.037530   
75%              0.722446                 0.641338                 0.760782   
max              3.600187                 3.477044                 4.124285   

        subscribed  
count  1000.000000  
mean      0.503000  
std       0.500241  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [25]:
X = df.drop('subscribed',axis=1)
y = df['subscribed']

In [26]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size=0.25, random_state=(42))

In [27]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(X_train,y_train)
y_pred = log_model.predict(X_test)

In [28]:
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1])

In [29]:
from sklearn.metrics import accuracy_score,classification_report

In [31]:
from sklearn.metrics import confusion_matrix
score = accuracy_score(y_pred ,y_test)
print("score : ",score)
print(classification_report(y_pred,y_test))
print("confusion matrix \n",confusion_matrix(y_pred,y_test))

score :  0.924
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       132
           1       0.91      0.93      0.92       118

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

confusion matrix 
 [[121  11]
 [  8 110]]


In [32]:
#hyperparameter tuning

In [33]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [34]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [35]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [36]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [37]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [38]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [39]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [40]:
grid.best_score_

np.float64(0.924)

In [41]:
y_pred=grid.predict(X_test)

In [42]:
score=accuracy_score(y_pred,y_test)
print("score: " , score)
print(classification_report(y_pred,y_test))
print("confusion matrix: \n" , confusion_matrix(y_pred,y_test))

score:  0.932
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       136
           1       0.90      0.96      0.93       114

    accuracy                           0.93       250
   macro avg       0.93      0.93      0.93       250
weighted avg       0.93      0.93      0.93       250

confusion matrix: 
 [[124  12]
 [  5 109]]


In [43]:
# random search

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [46]:
randomcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [47]:
randomcv.best_score_

np.float64(0.916)

In [48]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.1}

In [49]:
y_pred=randomcv.predict(X_test)

In [50]:
score=accuracy_score(y_pred,y_test)
print("score: " , score)
print(classification_report(y_pred,y_test))
print("confusion matrix: \n" , confusion_matrix(y_pred,y_test))

score:  0.92
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       133
           1       0.90      0.93      0.92       117

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

confusion matrix: 
 [[121  12]
 [  8 109]]
