<a href="https://colab.research.google.com/github/kzeynep/Python_Atil_hoca/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
np.array2string(np.array([[1,2],[3,4]]))

'[[1 2]\n [3 4]]'

In [5]:
type(np.array([[1,2],[3,4]]))

numpy.ndarray

In [6]:
myList = [10,20,30,40,50,60,70]

In [9]:
newList = np.array(myList)

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np_array =  np.arange(0,10)

In [14]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
np.random.randn(4,4)

array([[ 0.97639434,  0.92307078, -1.00768149,  0.71478514],
       [ 0.15981491, -0.95322628, -1.70606085,  0.75668573],
       [ 1.39002846,  0.11046681, -0.81325304, -0.33894048],
       [ 0.24388769, -1.03235993,  0.98712596, -0.2912535 ]])

In [17]:
np.random.randint(1,300,5)

array([193, 131, 272, 139,  94])

In [18]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[50,60],[70,80]])

In [19]:
first_array + second_array

array([[ 60,  80],
       [100, 120]])

In [21]:
first_matrix = np.array([[10,20,30]])

In [22]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [23]:
second_matrix = first_matrix.dot(second_matrix)

In [24]:
second_matrix

array([[120, 180]])

In [25]:
second_matrix.shape

(1, 2)

In [26]:
new_array = np.random.randint(1,100,20)

In [27]:
new_array

array([50, 83, 61, 81, 59, 37, 67, 42, 19, 17,  6, 18, 61, 18, 75, 59, 89,
       77, 20, 41])

In [28]:
new_array > 25

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True, False,  True,  True,  True,  True,
       False,  True])

In [29]:
new_array[new_array > 25]

array([50, 83, 61, 81, 59, 37, 67, 42, 61, 75, 59, 89, 77, 41])

In [30]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [31]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [32]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [33]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [34]:
random_array = np.random.random((6,1))

In [35]:
random_array

array([[0.503986  ],
       [0.21505193],
       [0.87463817],
       [0.51689516],
       [0.83774086],
       [0.33056394]])

In [37]:
random_array.shape

(6, 1)

In [38]:
random_array.reshape(2,3)

array([[0.503986  , 0.21505193, 0.87463817],
       [0.51689516, 0.83774086, 0.33056394]])

In [39]:
data = np.array([10,20,30,12,16,100,120,48])

In [40]:
mean = np.mean(data)

In [41]:
mean

np.float64(44.5)

In [42]:
std = np.std(data)

In [43]:
std

np.float64(39.78379066906521)

In [44]:
float(std)

39.78379066906521

In [45]:
# 2x + 3y = 8 and 5x + 7y = 19

In [46]:
A = np.array([[2,3],[5,7]])

In [47]:
B = np.array([8,19])

In [48]:
solution = np.linalg.solve(A,B)

In [49]:
solution

array([1., 2.])